version: '3.9'

services:
  web:
    image: hack:0.3
    container_name: fastapi_app
    ports:
      - "3001:3001"
 
  kafka:
    image: bitnami/kafka:4.0
    container_name: kafka
    ports:
      - "9092:9092"  # Порт для клиентов
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=your-cluster-id  # Уникальный ID кластера
    depends_on: 
      - web
  
  frontend:
    image: front_hack:0.1
    container_name: frontend
    ports:
      - "5500:5500"  #Если меняете этот порт, то пишите в тг: @vlados7529
    depends_on:
      - web  # Зависит от сервера (FastAPI)

volumes:
  kafkad_data:
